
PROGRAMA = MEAPILA

# primer fichero objeto (..\..\so1pub\lib\startlib.lib)
# segundo fichero objeto (..\..\so1pub\obj\ajustusr.obj)
# ultimo fichero objeto (..\so1pub\obj\fincode.obj)

OBJS2LINK =                      \
..\..\startfin\lib\startlib.lib, \
..\..\so1pub\obj\ajustusr.obj,   \
$(PROGRAMA).obj,                 \
..\..\so1pub\lib\ll_s_so1.lib,   \
..\..\so1pub\obj\tipos.obj,      \
..\..\so1pub\obj\stdio.obj,      \
..\..\so1pub\obj\vsprintf.obj,   \
..\..\so1pub\obj\scanner.obj,    \
..\..\so1pub\obj\strings.obj,    \
..\..\so1pub\obj\ctype.obj,      \
..\..\crtl\obj\h_ldiv.obj,       \
..\..\crtl\obj\h_lursh.obj,      \
..\..\crtl\obj\h_llsh.obj,       \
..\..\crtl\obj\f_lxmul.obj,      \
..\..\crtl\obj\n_lxmul.obj,      \
..\..\startfin\lib\finlib.lib

#puntero de pila inicial (finBSS = 0x2132 < 0x27FE)

SPINICIAL = 27FE

!include "..\..\MKFILE0"
!include "..\MAKEUSR"

!if (0) 
OBJS2LINK =                      \
..\..\startfin\lib\startlib.lib, \
..\..\so1pub\obj\ajustusr.obj,   \
$(PROGRAMA).obj,                 \
..\..\so1pub\lib\ll_s_so1.lib,   \
..\..\so1pub\obj\caracter.obj,   \
..\..\so1pub\obj\printgen.obj,   \
..\..\so1pub\obj\tipos.obj,      \
..\..\so1pub\obj\put.obj,        \
..\..\so1pub\obj\escribir.obj,   \
..\..\so1pub\obj\scanner.obj,    \
..\..\so1pub\obj\strings.obj,    \
..\..\crtl\obj\h_ldiv.obj,       \
..\..\crtl\obj\h_lursh.obj,      \
..\..\crtl\obj\h_llsh.obj,       \
..\..\crtl\obj\f_lxmul.obj,      \
..\..\crtl\obj\n_lxmul.obj,      \
..\..\startfin\lib\finlib.lib

#puntero de pila inicial (DATA = 813 BSS = 191F total: 2132 < 27FE)

SPINICIAL = 0FFE

!include "..\..\MKFILE0"
!include "..\MAKEUSR"
!endif
