!include "..\..\MKF0"

PROGS =   \
# programas de usuario "normales":
# --------------------------------
  atexit/   \
  ayuda/    \
  c2c/      \
  clock/    \
  date/     \
  dfs/      \
  dmp/      \
  dp/       \
  dr/       \
  exec/     \
  fork/     \
  hello/    \
  hello2/   \
  help/     \
  info/     \
  inic/     \
  kill/     \
  leetimer/ \
  login/    \
  meapila/  \
  mem/      \
  mouse/    \
  ps/       \
  sh/       \
  time/     \
  ver_args/ \
            \
# drivers:
# -------
  consola/  \
  raton/    \
  reloj/    \
  retardo/  \
  timer/    \

DIRS          = $(PROGS:/=)
DIRS.clean    = $(PROGS:/=.clean)
DIRS.pule     = $(PROGS:/=.pule)
DIRS.disquete = $(PROGS:/=.disquete)
DIRS.show     = $(PROGS:/=.show)
DIRS.hide     = $(PROGS:/=.hide)
DIRS.delsrc   = $(PROGS:/=.delsrc)

do: $(DIRS:help=)
  cd help
  $(MAKE)
  cd ..

$(DIRS:help=):
  cd $*
  $(MAKE)
  cd ..

build: clean disquete

disquete: $(DIRS.disquete)

$(DIRS.disquete):
  cd $*
  @"$(MAKE) disquete" | extraer +l 1
  @cd ..

clean: $(DIRS.clean)

$(DIRS.clean):
  cd $*
  @"$(MAKE) clean" | extraer +l 1
  @cd ..

pule: $(DIRS.pule)

$(DIRS.pule):
  cd $*
  @"$(MAKE) pule" | extraer +l 1
  @cd ..

show: $(DIRS.show)

$(DIRS.show):
  cd $*
  @"$(MAKE) show" | extraer +l 1
  @cd ..

hide: $(DIRS.hide)

$(DIRS.hide):
  cd $*
  @"$(MAKE) hide" | extraer +l 1
  @cd ..

delsrc: $(DIRS.delsrc)

$(DIRS.delsrc):
  cd $*
  @"$(MAKE) delsrc" | extraer +l 1
  @cd ..

run:
  cd ..\disquete
  @copy &&|
@mode con cols=80 lines=25
@so1.exe
@exit
| so1.cmd > nul
  @if %MSYSTEM%==MINGW64 (echo --------start so1.cmd & start so1.cmd)
  @if NOT %MSYSTEM%==MINGW64 (echo --------so1.cmd & so1.cmd)
# @if %MSYSTEM%==MINGW64 (start so1.exe)
# @if NOT %MSYSTEM%==MINGW64 (so1.exe)

runcom:
  cd ..\disquete
  @copy /Y ..\so1\so1.com so1.com
  @copy &&|
@mode con cols=80 lines=25
@msdos so1.com
@exit
| so1.bat > nul
  @if %MSYSTEM%==MINGW64 (echo --------start so1.bat & start so1.bat)
  @if NOT %MSYSTEM%==MINGW64 (echo --------so1.bat & so1.bat)
# @if %MSYSTEM%==MINGW64 (start msdos ..\so1\so1.com)
# @if NOT %MSYSTEM%==MINGW64 (msdos ..\so1\so1.com)

rundosbox:
# cd ..\disquete
# start $(UUSB):\Interno\dosbox-0.74\dosbox.exe so1.exe -noconsole -exit
  start $(UUSB):\Interno\dosbox-0.74\dosbox.exe ..\so1dbox.bat -noconsole -exit
  
rundosboxdbg:
  @echo.
# cd ..\disquete
# start $(UUSB):\Interno\dosbox-0.74\dosbox-74-debug.exe so1.exe -noconsole -exit
  start $(UUSB):\Interno\dosbox-0.74\dosbox-74-debug.exe ..\so1dbox.bat -noconsole -exit



DIRS.otrocomando = $(PROGS:/=.otrocomando)

otrocomando: $(DIRS.otrocomando)

$(DIRS.otrocomando):
  cd $*
# mkdir SOURCE
# copy *.C SOURCE
# if exist $*.C (move $*.C $*.COLD)
  if exist $*.COLD (erase $*.COLD)
# copy *.obj ..\_OCULTOS
  @cd ..

help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make            genera el .BIN de cada uno de los programas de usuario"
  @"echo    make pule       borra todo salvo los .BIN, fuentes y MAKEFILEs"
  @"echo    make clean      borra todo salvo los fuentes y MAKEFILEs"
  @"echo    make build      borra todo y genera nuevos ficheros .bin"
  @"echo    make run        ejecuta SO1.EXE en el directorio DISQUETE (Player)"
  @"echo    make runcom     ejecuta SO1.COM en el directorio DISQUETE (Player)"
  @"echo    make rundosbox  ejecuta SO1.EXE en el directorio DISQUETE (DOSBox)"
  @"echo    make show       mueve los ficheros .C de los directorios SOURCE"
  @"echo    make hide       mueve los ficheros .C a los directorios SOURCE"
  @"echo                    y guarda los .OBJ en los directorios _OCULTOS"
  @"echo    make help       muestra esta ayuda sobre los objetivos disponibles"
