
PROGRAMA = RATON

# primer fichero objeto (..\so1pub\obj\ajustusr.obj)
# ultimo fichero objeto (..\so1pub\obj\fincode.obj)

OBJS2LINK =                      \
..\..\startfin\lib\startlib.lib, \
..\..\so1pub\obj\ajustusr.obj,   \
$(PROGRAMA).obj,                 \
..\..\so1pub\lib\ll_s_so1.lib,   \
..\..\so1pub\obj\caracter.obj,   \
..\..\so1pub\obj\printgen.obj,   \
..\..\so1pub\obj\tipos.obj,      \
..\..\so1pub\obj\put.obj,        \
..\..\so1pub\obj\escribir.obj,   \
..\..\so1pub\obj\scanner.obj,    \
..\..\so1pub\obj\strings.obj,    \
..\..\so1pub\obj\copia.obj,      \
..\..\so1pub\obj\cmos.obj,       \
..\..\so1pub\obj\puertos.obj,    \
..\..\so1pub\obj\pantalla.obj,   \
..\..\so1pub\obj\crthw.obj,      \
..\..\so1pub\obj\bios_0.obj,     \
..\..\so1pub\obj\bios_crt.obj,   \
..\..\so1pub\obj\bios_rat.obj,   \
..\..\so1pub\obj\msdos.obj,      \
..\..\so1pub\obj\memvideo.obj,   \
..\..\so1pub\obj\ptrc2c.obj,     \
..\..\so1pub\obj\pic.obj,        \
..\..\so1pub\obj\debug.obj,      \
..\..\crtl\obj\h_ldiv.obj,       \
..\..\crtl\obj\h_lursh.obj,      \
..\..\crtl\obj\h_llsh.obj,       \
..\..\crtl\obj\f_lxmul.obj,      \
..\..\crtl\obj\n_lxmul.obj,      \
..\..\startfin\lib\finlib.lib

#puntero de pila inicial (DATA = 6F5 BSS = 154F total: 1C44 < 1FFF)

SPINICIAL = 1FFE

!include "..\..\MKFILE0"
!include "..\MAKEUSR"
