/* ----------------------------------------------------------------------- */
/*                               caracter.h                                */
/* ----------------------------------------------------------------------- */
/*                                                                         */
/* ----------------------------------------------------------------------- */

#ifndef CARACTER_H
#define CARACTER_H

extern char dig[17] ;

char mayuscula ( char letra ) ;

char minuscula ( char letra ) ;

#endif /* CARACTER_H */

