/* ----------------------------------------------------------------------- */
/*                                  const.h                                */
/* ----------------------------------------------------------------------- */
/*                     principales constantes del sistema                  */
/* ----------------------------------------------------------------------- */

#ifndef CONST_H
#define CONST_H

//#define maxProcesos 20                      /* numero maximo de procesos */
#define maxProcesos 16                        /* numero maximo de procesos */

#define dfMax 10   /* numero maximo de descriptores de fichero del proceso */

#define dfsMax 20  /* numero maximo de descriptores de fichero del sistema */

#define maxRecursos 14                        /* numero maximo de recursos */

#define nVIntMax 128 /* 256 */

#endif /* CONST_H */

