/* ----------------------------------------------------------------------- */
/*                                 copia.h                                 */
/* ----------------------------------------------------------------------- */
/*                                                                         */
/* ----------------------------------------------------------------------- */

#ifndef COPIA_H
#define COPIA_H

#include <so1pub.h\tipos.h>

void copia ( pointer_t origen, pointer_t destino, word_t tam ) ;

void copiaLarga ( pointer_t origen, pointer_t destino, dword_t tam ) ;

#endif /* COPIA_H */

