/* ----------------------------------------------------------------------- */
/*                                saludos.h                                */
/* ----------------------------------------------------------------------- */
/*                 mensajes que se muestran al inicio de SO1               */
/* ----------------------------------------------------------------------- */

#ifndef SALUDOS_H
#define SALUDOS_H

void printStrRojo ( char * str ) ;

void mostrarSaludoGrande ( void ) ;

void mostrarSaludo ( void ) ;

#endif /* SALUDOS_H */
