
PROGRAMA = CONTKD

# primer fichero objeto (..\..\so1pub\lib\startlib.lib)
# segundo fichero objeto (..\..\so1pub\obj\ajustusr.obj)
# ultimo fichero objeto (..\so1pub\obj\fincode.obj)

OBJS2LINK =                      \
..\..\startfin\lib\startlib.lib, \
..\..\so1pub\obj\ajustusr.obj,   \
#..\..\so1pub\obj\debug.obj,  \     (aqui da problemas ¿alineado?)
#
..\..\so1pub\obj\ptrc2c.obj,     \
..\..\so1pub\obj\memory.obj,     \
..\..\so1pub\obj\pantalla.obj,   \
..\..\so1pub\obj\bios_crt.obj,   \
..\..\so1pub\obj\bios_0.obj,     \
..\..\so1pub\obj\memvideo.obj,   \
..\..\so1pub\obj\crthw.obj,      \
# (printgen requiere h_ldiv.obj)   
..\..\so1pub\obj\printgen.obj,   \
..\..\crtl\obj\h_ldiv.obj,       \
$(PROGRAMA).obj,                 \
#
..\..\so1pub\obj\debug.obj,      \
..\..\so1pub\lib\ll_s_so1.lib,   \
..\..\so1pub\obj\comundrv.obj,   \
..\..\so1pub\obj\ctype.obj,      \
..\..\so1pub\obj\stdio.obj,      \
# (vsprintf requiere h_ldiv.obj)   
..\..\so1pub\obj\vsprintf.obj,   \
..\..\so1pub\obj\scanner.obj,    \
..\..\so1pub\obj\strings.obj,    \
#..\..\crtl\obj\h_ldiv.obj,       \
..\..\crtl\obj\h_lursh.obj,      \
..\..\crtl\obj\h_llsh.obj,       \
..\..\crtl\obj\f_lxmul.obj,      \
..\..\crtl\obj\n_lxmul.obj,      \
..\..\startfin\lib\finlib.lib

#puntero de pila inicial (finBSS = 2868 < 2FFE)

SPINICIAL = 2FFE

!include "..\..\MKFILE0"

COMPILACIONDIRECTA = 0 

!include "..\MAKEUSR"
