/* ----------------------------------------------------------------------- */
/*                                 minisf.h                                */
/* ----------------------------------------------------------------------- */
/*                                                                         */
/* ----------------------------------------------------------------------- */

#ifndef MINISF_H
#define MINISF_H

extern rindx_t rec_sf ;

extern dfs_t dfs_sf ;

int inicMinisfMSDOS ( void ) ;

int inicMinisfFAT ( void ) ;

#endif /* MINISF_H */
