
PROGRAMA = INIC

# primer fichero objeto (..\..\so1pub\lib\startlib.lib)
# segundo fichero objeto (..\..\so1pub\obj\ajustusr.obj)
# ultimo fichero objeto (..\so1pub\obj\fincode.obj)

OBJS2LINK =                      \
..\..\startfin\lib\startlib.lib, \
..\..\so1pub\obj\ajustusr.obj,   \
$(PROGRAMA).obj,                 \
..\..\so1pub\lib\ll_s_so1.lib,   \
..\..\so1pub\obj\tipos.obj,      \
..\..\so1pub\obj\stdio.obj,      \
..\..\so1pub\obj\vsprintf.obj,   \
..\..\so1pub\obj\ctype.obj,      \
..\..\so1pub\obj\strings.obj,    \
..\..\so1pub\obj\scanner.obj,    \
..\..\so1pub\obj\leercmd.obj,    \
..\..\so1pub\obj\interpre.obj,   \
..\..\so1pub\obj\saludos.obj,    \
..\..\so1pub\obj\msdos.obj,      \
#..\..\so1pub\obj\printgen.obj,   \
#..\..\so1pub\obj\put.obj,        \
#..\..\so1pub\obj\memory.obj,     \
#..\..\so1pub\obj\bios_0.obj,     \
..\..\crtl\obj\h_ldiv.obj,       \
..\..\crtl\obj\h_lursh.obj,      \
..\..\crtl\obj\h_llsh.obj,       \
..\..\crtl\obj\f_lxmul.obj,      \
..\..\crtl\obj\n_lxmul.obj,      \
..\..\startfin\lib\finlib.lib

#puntero de pila inicial (finBSS = 1656 < 17FE)

SPINICIAL = 17FE

!include "..\..\MKFILE0"
!include "..\MAKEUSR"
