!include "\SO\MKF0"

DIRS = crtl/ \
       so1pub/ \
       startfin/ \
       _mbr/ _pbrfat16/ \
       so1/ \
       progusr/


DIRS.do       = $(DIRS:/=.do)
DIRS.clean    = $(DIRS:/=.clean)
DIRS.show     = $(DIRS:/=.show)
DIRS.hide     = $(DIRS:/=.hide)
DIRS.delsrc   = $(DIRS:/=.delsrc)

disquete: $(DIRS.do)

$(DIRS.do):
  cd $*
# @"$(MAKE) " | extraer +l 1
  @"$(MAKE) "
  @cd ..


clean: $(DIRS.clean) clearDisquete
  @if exist stderr.txt erase stderr.txt
  @if exist stdout.txt erase stdout.txt

$(DIRS.clean):
  cd $*
  @"$(MAKE) clean" | extraer +l 1
  @cd ..

clearDisquete:
  cd disquete
  @if exist *.* erase /Q *.*
  @cd ..

pule: crtl.clean so1pub.clean startfin.clean progusr.clean so1.clean
  cd disquete
  @if exist stderr.txt erase stderr.txt
  @if exist stdout.txt erase stdout.txt
  cd ..
  cd _MBR
  @"$(MAKE) pule" | extraer +l 1
  @cd ..
  cd _PBRFAT16
  @"$(MAKE) pule" | extraer +l 1
  cd _BPBFAT16
  @"$(MAKE) pule" | extraer +l 1
  @cd ..
  @cd ..
  
show: $(DIRS.show)

$(DIRS.show):
  cd $*
  @"$(MAKE) show" | extraer +l 1
  @cd ..

hide: $(DIRS.hide)

$(DIRS.hide):
  cd $*
  @"$(MAKE) hide" | extraer +l 1
  @cd ..

delsrc: $(DIRS.delsrc)

$(DIRS.delsrc):
  cd $*
  @"$(MAKE) delsrc" | extraer +l 1
  @cd ..

build: clean disquete

shell:
  cd so1pub
  if exist interpre.c (touch interpre.c)
  make obj\interpre.obj
  cd ..\so1
  if exist iniccode.c (touch iniccode.c)
  make obj\iniccode.obj
  cd ..\progusr\sh
  make
  cd ..\inic
  make
  cd ..\..

run:
  cd disquete
  @copy &&|
@mode con cols=80 lines=25
@so1.exe
@exit
| so1.cmd > nul
  @if %MSYSTEM%==MINGW64 (echo --------start so1.cmd & start so1.cmd)
  @if NOT %MSYSTEM%==MINGW64 (echo --------so1.cmd & so1.cmd)
# @if %MSYSTEM%==MINGW64 (echo --------start so1.exe & start so1.exe)
# @if NOT %MSYSTEM%==MINGW64 (echo --------so1.exe & so1.exe)

runcom:
  cd disquete
  @copy /Y ..\so1\so1.com so1.com
  @copy &&|
@mode con cols=80 lines=25
@msdos so1.com
@exit
| so1.bat > nul
  @if %MSYSTEM%==MINGW64 (echo --------start so1.bat & start so1.bat)
  @if NOT %MSYSTEM%==MINGW64 (echo --------so1.bat & so1.bat)
# @if %MSYSTEM%==MINGW64 (echo --------start msdos ..\so1\so1.com & start msdos ..\so1\so1.com)
# @if NOT %MSYSTEM%==MINGW64 (echo --------msdos ..\so1\so1.com & msdos ..\so1\so1.com)

rundosbox:
# cd disquete
# start $(UUSB):\Interno\dosbox-0.74\dosbox.exe so1.exe -noconsole -exit
  start $(UUSB):\Interno\dosbox-0.74\dosbox.exe so1dbox.bat -noconsole -exit

rundosboxdbg:
# cd disquete
# start $(UUSB):\Interno\dosbox-0.74\dosbox-74-debug.exe so1.exe -noconsole -exit
  start $(UUSB):\Interno\dosbox-0.74\dosbox-74-debug.exe so1dbox.bat -noconsole -exit 

help:
# echo off & color 07 & title help & msg * "Hola"
  @"echo."
  @"echo    relacion de objetivos disponibles:"
  @"echo."
  @"echo    make           genera SO1.BIN y SO1.EXE y los copia en DISQUETE"
  @"echo    make clean     borra todo salvo los fuentes y ficheros MAKEFILE"
  @"echo    make build     borra todo y genera de nuevo (make clean + make)"
  @"echo    make disquete  copia SO1.BIN y SO1.EXE en el directorio DISQUETE"
  @"echo    make shell     recompila interpre.c y actualiza SH.BIN e INIC.BIN"
  @"echo    make run       ejecuta SO1.EXE en el directorio DISQUETE (Player)"
  @"echo    make runcom    ejecuta SO1.COM en el directorio DISQUETE (Player)"
  @"echo    make rundosbox ejecuta SO1.EXE en el directorio DISQUETE (DOSBox)"
  @"echo    make show      mueve los ficheros .C de los directorios SOURCE"
  @"echo    make hide      mueve los ficheros .C a los directorios SOURCE"
  @"echo                   y guarda los .OBJ en los directorios _OCULTOS"
  @"echo    make help      muestra esta ayuda sobre los objetivos disponibles"
