!include "..\..\MKFILE0"

PROGRAMA = VER_FICH

disquete: ..\..\DISQUETE\$(PROGRAMA).bin

..\..\DISQUETE\$(PROGRAMA).bin: $(PROGRAMA).bin
  @if exist $@ del $@
  copy $** $:

$(PROGRAMA).bin: $(PROGRAMA).org
  @echo.
  @copy $(PROGRAMA).org $(PROGRAMA).BIN

clean:
  @if exist $(PROGRAMA).bin erase $(PROGRAMA).bin

build: 
  @rem

show:
  @rem

delsrc:
  @rem

hide:
  @rem
  
run: disquete
  cd ..\..\disquete
  so1.exe
  
