/* ----------------------------------------------------------------------- */
/*                               interpre.h                                */
/* ----------------------------------------------------------------------- */
/*                     interpretacion de los comandos                      */
/* ----------------------------------------------------------------------- */

#ifndef INTERPRE_H
#define INTERPRE_H

int redirigirSTDIO ( char * nombreDispositivo ) ;

int interpretarComandos ( void ) ;

#endif /* INTERPRE_H */

