/***************************************************************************/
/*                              startdata.c                                */
/***************************************************************************/
/*    Funcion nula en el segmento de datos para determinar algun punto     */
/*           del segmento de datos en el momento del enlazado              */
/***************************************************************************/

#ifndef STARTDATA_H
#define STARTDATA_H

/* startData:                                                              */
/*   Funcion en el segmento de datos sin ningun codigo (y sin retorno).    */
/*   Apropiada para determinar un punto del segmento de datos en el        */
/*   momento del enlazado.                                                 */

void startData ( void ) ;

#endif /* STARTDATA_H */